/**
 * This file is auto-generated by Payload CMS.
 * Run `npm run generate:types` after connecting to the database to regenerate.
 * This placeholder allows TypeScript to compile before the database is connected.
 */

export interface User {
  id: string
  email: string
  updatedAt: string
  createdAt: string
}

export interface Media {
  id: string
  alt: string
  url?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  updatedAt: string
  createdAt: string
}

export interface Project {
  id: string
  title: string
  slug: string
  category: 'interior-design' | 'wine' | 'commercial' | 'residential' | 'heritage' | 'before-after'
  featured?: boolean | null
  heroImage: string | Media
  gallery?: Array<{
    image: string | Media
    caption?: string | null
    id?: string | null
  }> | null
  shortDescription: string
  description?: unknown
  location?: string | null
  year?: number | null
  client?: string | null
  publishedAt?: string | null
  seo?: {
    metaTitle?: string | null
    metaDescription?: string | null
  }
  updatedAt: string
  createdAt: string
}

export interface BlogPost {
  id: string
  title: string
  slug: string
  status: 'draft' | 'published'
  heroImage?: string | Media | null
  excerpt?: string | null
  content?: unknown
  category?: 'news' | 'project-update' | 'industry' | 'behind-the-scenes' | null
  author?: string | User | null
  publishedAt?: string | null
  seo?: {
    metaTitle?: string | null
    metaDescription?: string | null
  }
  updatedAt: string
  createdAt: string
}

export interface Service {
  id: string
  title: string
  slug: string
  tagline?: string | null
  description?: unknown
  icon?: 'pencil-ruler' | 'home' | 'building' | 'wine-glass' | null
  includes?: Array<{ item: string; id?: string | null }> | null
  order?: number | null
  updatedAt: string
  createdAt: string
}

export interface Config {
  collections: {
    users: User
    media: Media
    projects: Project
    'blog-posts': BlogPost
    services: Service
  }
}
