/**
 * This file is auto-generated by Payload CMS.
 * Run `npm run generate:types` after connecting to the database to regenerate.
 */

export interface User {
  id: string
  email: string
  name: string
  role: 'admin' | 'editor'
  hash?: string
  salt?: string
  updatedAt: string
  createdAt: string
}

export interface Media {
  id: string
  alt: string
  caption?: string | null
  credit?: string | null
  url?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  sizes?: Record<string, { url: string; width: number; height: number }> | null
  updatedAt: string
  createdAt: string
}

export interface Project {
  id: string
  title: string
  slug: string
  category: string
  featured?: boolean
  heroImage?: string | Media | null
  gallery?: Array<{ image: string | Media; caption?: string; id?: string }> | null
  shortDescription: string
  description?: unknown
  location?: string | null
  year?: number | null
  client?: string | null
  publishedAt?: string | null
  seo?: { metaTitle?: string; metaDescription?: string }
  updatedAt: string
  createdAt: string
}

export interface BlogPost {
  id: string
  title: string
  slug: string
  status: 'draft' | 'published'
  heroImage?: string | Media | null
  excerpt?: string
  content?: unknown
  category?: string | null
  author?: string | User | null
  publishedAt?: string | null
  seo?: { metaTitle?: string; metaDescription?: string }
  updatedAt: string
  createdAt: string
}

export interface Service {
  id: string
  title: string
  slug: string
  tagline?: string
  description?: unknown
  icon?: string | null
  includes?: Array<{ item: string; id?: string }> | null
  order?: number
  updatedAt: string
  createdAt: string
}

export interface Config {
  collections: {
    users: User
    media: Media
    projects: Project
    'blog-posts': BlogPost
    services: Service
  }
}